import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#000]">
      <body
        className="geist_... geist_mono_... max-w-[1240px] w-full mx-auto"
        data-new-gr-c-s-check-loaded="14.1272.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
      >
        {children}
      </body>
    </html>
  );
}
